spring:
  config:
    import: optional:file:../../../shared-configuration/application-common-dev.yaml
  application:
    name: booking-service
  datasource:
    url: ${DATABASE_HOST}/booking-service

server:
  port: 8083
