spring:
  config:
    import: optional:file:../../../shared-configuration/application-common-dev.yaml
  application:
    name: user-service
  datasource:
    url: ${DATABASE_HOST}/user-service

server:
  port: 8081
